production:
  server: "https://< app name >.herokuapp.com/faye" 

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension. 

  secret_token: "d7bcb26b448dc7b8cda73a7b46b62a8f079375726243716d6f827dfb4ab28c87"
  signature_expiration: 3600 # one day
